sudo: required
language: generic
services:
                - docker

before_install:
        - docker build -t aa/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true aa/docker-react npm run test
